book:
    # - 00-Assignment.qmd
    # - 01-Introduction.qmd
    # - 02-Statistics-Review.qmd
    # - 03-linear-difference-equations.qmd
    # - 04-AR.qmd
    # - 05-Model-Fitting.qmd
    # - 06-Unit-Root-Tests.qmd
    # - 08-ARIMA-Forecasting.qmd
    # - 09-GARCH.qmd
    # - references.qmd
  google-analytics: G-4SEWJRKMLS
  cookie-consent: true


format:
  html:
    theme: cosmo
