project:
  type: book
  output-dir: _site

book:
  title: "Introduction to Time Series Analysis 2024/2025"
  author: "Boyko Amarov"
  date: "10/1/2024"
  chapters:
    - index.qmd
    # - 00-Assignment.qmd
    - 00-Homework.qmd
    - 01-Introduction.qmd
    - 02-Linear-Difference-Equations.qmd
    - 03-Statistics-Review.qmd
    - 04-AR.qmd
    - 05-AR-Model-Fitting.qmd
    - 06-ARIMA-Forecasting.qmd
    - 07-Unit-Root-Tests.qmd
    - 08-GARCH.qmd
    # - 04-AR.qmd
    # - 05-Model-Fitting.qmd
    # - 06-Unit-Root-Tests.qmd
    # - 08-ARIMA-Forecasting.qmd
    # - 09-GARCH.qmd
    - 09-ANN.ipynb
    - 10-Skew.qmd
    - references.qmd

bibliography: refs.bib

format:
  html:
    theme: cosmo
